### ISSUE TITLE
Need more infinite oscillations

### ISSUE THREAD

**Issue by multiojuice** [CrownSterlingIO/quantum-ai-crypt-python#4]
Need more infinite oscillations, might ask my AI to generate a PR for this later.

**Comment by tarcieri** [comment]
The core problem seems to be the current usage of quasi-primes is constrained to ℵ₀. However, per the continuum hypothesis we know that 2<sup>ℵ₀</sup> = ℵ₁. Based on this, you can obtain infinite infinite oscillations by recursing through fixed points of ω:

ω₁, ω<sub>ω₁</sub>, ω<sub>ω<sub>ω₁</sub></sub>, ...
